In [2]:
import pandas as pd
import numpy as np
incidents = pd.read_csv("C:/Users/user/Desktop/Python_Main/kurs_pandas/Canadian Railway Crossing Incidents.csv")

In [3]:
incidents.set_index(["Region","EventType"],inplace = True)
incidents.sort_index(inplace=True)

In [4]:
incidents.head(10)

                                   Public automated  Public passive  Private  \
Region           EventType
Alberta          Accidents                        3               7        2
                 Fatalities                       0               0        0
                 Serious injuries                 0               1        2
British Columbia Accidents                        4               1        0
                 Fatalities                       0               0        0
                 Serious injuries                 3               0        0
Manitoba         Accidents                        1               3        0
                 Fatalities                       0               1        0
                 Serious injuries                 0               0        0
New Brunswick    Accidents                        0               0        0

                                   Farm
Region           EventType
Alberta          Accidents            0
                 Fatalities           0
                 Serious injuries     0
British Columbia Accidents            0
                 Fatalities           0
                 Serious injuries     0
Manitoba         Accidents            2
                 Fatalities           0
                 Serious injuries     1
New Brunswick    Accidents            0

In [5]:
incidents.stack().head()

Region   EventType
Alberta  Accidents   Public automated    3
                     Public passive      7
                     Private             2
                     Farm                0
         Fatalities  Public automated    0
dtype: int64

In [6]:
incidents.stack().to_frame().head()

                                     0
Region  EventType
Alberta Accidents  Public automated  3
                   Public passive    7
                   Private           2
                   Farm              0
        Fatalities Public automated  0

In [7]:
stackIncidents = incidents.stack().to_frame()

In [8]:
stackIncidents

                                                0
Region       EventType
Alberta      Accidents        Public automated  3
                              Public passive    7
                              Private           2
                              Farm              0
             Fatalities       Public automated  0
...                                            ..
Saskatchewan Fatalities       Farm              0
             Serious injuries Public automated  0
                              Public passive    0
                              Private           0
                              Farm              0

[120 rows x 1 columns]

In [12]:
stackIncidents.unstack().unstack().head()

                                0                                             \
                 Public automated                             Public passive
EventType               Accidents Fatalities Serious injuries      Accidents
Region
Alberta                         3          0                0              7
British Columbia                4          0                3              1
Manitoba                        1          0                0              3
New Brunswick                   0          0                0              0
Newfoundland                    0          0                0              0

                                                                   \
                                               Private
EventType        Fatalities Serious injuries Accidents Fatalities
Region
Alberta                   0                1         2          0
British Columbia          0                0         0          0
Manitoba                  1                0         0          0
New Brunswick             0                0         0          0
Newfoundland              0                0         0          0


                                       Farm
EventType        Serious injuries Accidents Fatalities Serious injuries
Region
Alberta                         2         0          0                0
British Columbia                0         0          0                0
Manitoba                        0         2          0                1
New Brunswick                   0         0          0                0
Newfoundland                    0         0          0                0